template_path: templates/bastion.yaml


parameters:
  ResourcePrefix: davedev
  VpcId: !stack_output vpc::VpcId
  SubnetAZ0Id: !stack_output vpc::PublicSubnetAZ0
  SubnetAZ1Id: !stack_output vpc::PublicSubnetAZ1
  KeypairName: dliggat-tam
  AmiId: daveami
  InstanceType: t2.xlarge


