AWSTemplateFormatVersion: "2010-09-09"

Description: A standard VPC.

Parameters:
  ResourcePrefix:
    Type: String
    Description: A description to identify resources (e.g. "my-perf-test")

  VpcCidr:
    Type: String
    Description: A network CIDR e.g. "10.0.0.0/16"

  
  PublicSubnetAZ0Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.0.0/24"

  PrivateSubnetAZ0Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.10.0/24"

  
  PublicSubnetAZ1Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.1.0/24"

  PrivateSubnetAZ1Cidr:
    Type: String
    Description: A subnet CIDR e.g. "10.0.11.0/24"

  

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: True
      EnableDnsHostnames: True
      InstanceTenancy: default
      CidrBlock: { Ref: VpcCidr }
      Tags: [ { Key: Name, Value: { Ref: ResourcePrefix } } ]

  DHCPSettings:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainNameServers:  [ "AmazonProvidedDNS" ]
      DomainName:  ec2-internal

  DHCPSettingsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId: { "Ref" : "Vpc" }
      DhcpOptionsId: { "Ref" : "DHCPSettings" }

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "internetgateway"

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: { "Ref": "Vpc" }
      InternetGatewayId : { "Ref" : "InternetGateway" }

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: { Ref : Vpc }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "rtb"
                - "public"

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: { "Ref": "Vpc" }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "rtb"
                - "private"

  RoutePublicToInternet:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId:  { Ref: PublicRouteTable }
      GatewayId:     { Ref: InternetGateway }

  
  PublicSubnetAZ0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
      MapPublicIpOnLaunch: "true"
      CidrBlock: { Ref: PublicSubnetAZ0Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "public"
                - { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPublicAZ0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PublicSubnetAZ0 }
      RouteTableId: { Ref: PublicRouteTable }

  PrivateSubnetAZ0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
      CidrBlock: { Ref: PrivateSubnetAZ0Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "private"
                - { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPrivateAZ0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PrivateSubnetAZ0 }
      RouteTableId: { Ref: PrivateRouteTable }

  
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
      MapPublicIpOnLaunch: "true"
      CidrBlock: { Ref: PublicSubnetAZ1Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "public"
                - { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPublicAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PublicSubnetAZ1 }
      RouteTableId: { Ref: PublicRouteTable }

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: Vpc }
      AvailabilityZone: { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
      CidrBlock: { Ref: PrivateSubnetAZ1Cidr }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "private"
                - { "Fn::Select": [ "1", { "Fn::GetAZs": "" } ] }
  SubnetRouteTableAssociationPrivateAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PrivateSubnetAZ1 }
      RouteTableId: { Ref: PrivateRouteTable }

  

Outputs:
  DefaultSecurityGroupId:
    Value:
      "Fn::GetAtt": [Vpc, DefaultSecurityGroup]
  VpcId:
    Value: { Ref: Vpc }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ResourcePrefix }
            - "VpcId"

  
  PublicSubnetAZ0:
    Value: { Ref: PublicSubnetAZ0 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ResourcePrefix }
            - PublicSubnetAZ0

  PrivateSubnetAZ0:
    Value: { Ref: PrivateSubnetAZ0 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ResourcePrefix }
            - PrivateSubnetAZ0

  
  PublicSubnetAZ1:
    Value: { Ref: PublicSubnetAZ1 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ResourcePrefix }
            - PublicSubnetAZ1

  PrivateSubnetAZ1:
    Value: { Ref: PrivateSubnetAZ1 }
    Export:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ResourcePrefix }
            - PrivateSubnetAZ1

  

