template_path: templates/singleton-asg.yaml


parameters:
  ResourcePrefix: {{ project_code }}
  VpcId: !stack_output vpc::VpcId
  SubnetAZ0Id: !stack_output vpc::PublicSubnetAZ0
  SubnetAZ1Id: !stack_output vpc::PublicSubnetAZ1
  KeypairName: dliggat-tam
  InstanceType: t2.xlarge
